image: stackstate/tcptracer-bpf-builder:latest

stages:
  - test

test:
  stage: test
  script:
    # Proc root is set by the gitlab ci runner
    - export TEST_PROC_ROOT=/host/proc
    - mkdir -p /go/src/github.com/StackVista
    - cp -a $CI_PROJECT_DIR /go/src/github.com/StackVista/tcptracer-bpf
    - export GOPATH=/go
    - cd /go/src/github.com/StackVista/tcptracer-bpf
    - make ci-test
  tags:
    # Run on sts hardware to be able to test ebpf
    - sts-aws

