
required = ["github.com/mailru/easyjson", "github.com/iovisor/gobpf"]

[[constraint]]
  name = "github.com/cihub/seelog"
  version = "=v2.6"

[[constraint]]
  name = "github.com/pytimer/win-netstat"
  revision = "efa1aff6aafc7b37ca3ffb136b6b27a11178ffd6"

[[constraint]]
  name = "github.com/DataDog/sketches-go"
  source = "github.com/StackVista/sketches-go"
  version = "=v1.1.0"

[[constraint]]
  name = "github.com/iovisor/gobpf"
  source = "github.com/StackVista/gobpf"
  version = "=v0.1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.7.0"

[[constraint]]
  name = "github.com/mailru/easyjson"
  version = "=v0.7.7"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/iovisor/gobpf"
  unused-packages = false
