version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: /home/circleci/go/src/github.com/StackVista/tcptracer-bpf
    environment:
      TEST_PROC_ROOT: /host/proc
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - run: ./bootstrap.sh
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: $GOPATH/bin/dep ensure
      - run: make linux-ci-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
